import { Metadata } from "next";
import UI from "./UI";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Home() {
    return <UI />;
}
